name: pawlly_employee
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.3.2+37

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^17.2.3

  nb_utils: ^7.1.7+2
  google_fonts: ^6.3.0
  html: ^0.15.6
  http: ^1.5.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  share_plus: ^11.1.0
  stream_transform: ^2.1.1
  omni_datetime_picker: ^2.2.0
  path_provider: ^2.1.5
  playx_version_update: ^1.0.0

  # SOCIAL LOGIN
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.2.1
  permission_handler: ^12.0.0+1

  # State Management
  get: ^4.7.2

  #Storage
  get_storage: ^2.1.1

  #intent
  android_intent_plus: ^5.3.1

  datepicker_dropdown: ^1.0.1
  file_picker: ^10.3.2
  image_picker: ^1.2.0
  country_picker: ^2.0.27

  # MAP
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  #PhotoViewGallery
  photo_view: ^0.15.0

  #SHIMMER
  shimmer: ^3.0.0

  flutter_localizations:
    sdk: flutter
  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/icons/
    - assets/images/services/
    - assets/images/pet_profile/
    - assets/images/notification/
    - assets/icons/profile_icons/
    - assets/icons/navigation/
    - assets/icons/service_icons/
    - assets/lottie/
    - assets/images/emp_icon/
    - assets/images/auth_images/